[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"
[build.environment]
  NODE_VERSION = "14"
[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "build"
  framework = "#custom"